/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.Controller;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tools.Global;
import interfaces.GraphModel;
import java.io.FileNotFoundException;
import models.SeriesChartPane;
import models.BrainOverlay;


/**
 *
 * @author thy
 */
public class View extends javax.swing.JFrame {
    Controller cont = new Controller();
    /**
     * Creates new form view
     */
    public View() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabBrain = new javax.swing.JPanel();
        leftMain = new javax.swing.JPanel();
        rightMain = new javax.swing.JPanel();
        tabEEG = new javax.swing.JPanel();
        leftEEG = new javax.swing.JPanel();
        rightEEG = new javax.swing.JPanel();
        tabRegion1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tabRegion2 = new javax.swing.JPanel();
        tabRegion3 = new javax.swing.JPanel();
        tabRegion4 = new javax.swing.JPanel();
        tabRegion5 = new javax.swing.JPanel();
        tabRegion6 = new javax.swing.JPanel();
        tabRegion7 = new javax.swing.JPanel();
        tabRegion8 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        NIRSTester = new javax.swing.JMenuItem();
        navi = new javax.swing.JMenu();
        back = new javax.swing.JMenuItem();
        forward = new javax.swing.JMenuItem();
        home = new javax.swing.JMenuItem();
        actions = new javax.swing.JMenu();
        start = new javax.swing.JMenuItem();
        stop = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multimodal Neural Monitoring");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        tabBrain.setLayout(new javax.swing.BoxLayout(tabBrain, javax.swing.BoxLayout.LINE_AXIS));

        leftMain.setBorder(BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout leftMainLayout = new javax.swing.GroupLayout(leftMain);
        leftMain.setLayout(leftMainLayout);
        leftMainLayout.setHorizontalGroup(
            leftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );
        leftMainLayout.setVerticalGroup(
            leftMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        tabBrain.add(leftMain);

        rightMain.setLayout(new java.awt.GridBagLayout());
        rightMain.setBorder(BorderFactory.createTitledBorder(""));
        rightMain.setBackground(Color.white);
        setResizable(false);
        
        cont.implementRegionImages(rightMain, jTabbedPane1);

        tabBrain.add(rightMain);

        jTabbedPane1.addTab("Main", tabBrain);

        tabEEG.setLayout(new javax.swing.BoxLayout(tabEEG, javax.swing.BoxLayout.LINE_AXIS));


        leftEEG.setBorder(BorderFactory.createTitledBorder(""));
        leftEEG.setLayout(new java.awt.GridLayout(0, 1));
        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            leftEEG.add(new SeriesChartPane(model));
            leftEEG.add(new SeriesChartPane(model));
            leftEEG.add(new SeriesChartPane(model));
            leftEEG.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }
        tabEEG.add(leftEEG);

        rightEEG.setBorder(BorderFactory.createTitledBorder(""));
        rightEEG.setBackground(Color.WHITE);
        rightEEG.setLayout(new GridBagLayout());
        //GridBagConstraints GBC = new GridBagConstraints();
        

        //try {
            //    BufferedImage eeg = ImageIO.read(new File("src/images/updated_eeg_map.png"));
            //
            //    ArrayList<BufferedImage> abiRegions = new ArrayList<BufferedImage>();
            //    ArrayList<ImageIcon> aiRegions = new ArrayList<ImageIcon>();
            //    ArrayList<JLabel> ajlRegions = new ArrayList<JLabel>();
            //    ImageMap imageSlice = new ImageMap(eeg, abiRegions, aiRegions, ajlRegions);
            //    for(int i = 0; i < ajlRegions.size(); i++) {
                //        rightEEG.add(ajlRegions.get(i));
                //    }

            //} catch (IOException e) {
            //    // TODO Auto-generated catch block
            //    e.printStackTrace();
            //}

        try {
            BufferedImage eeg = ImageIO.read(new File("src/images/updated_eeg_map.png"));
            JLabel picLabel = new JLabel(new ImageIcon(eeg));
            //picLabel.setVerticalAlignment(1);
            rightEEG.add(picLabel);
            
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        tabEEG.add(rightEEG);

        jTabbedPane1.addTab("EEG", tabEEG);

        tabRegion1.setLayout(new java.awt.GridLayout(2, 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Status:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Good");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion1.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Oxygenation");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("78%");

        jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Temperature");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion1.add(jPanel4);

        //try {
            //    GraphModel model = new models.NIRSGraphModel();
            //    tabRegion1.add(new SeriesChartPane(model));
            //}
        //catch (FileNotFoundException e) {
            //    System.out.println("oh no");
            //}

        jTabbedPane1.addTab("Region 1", tabRegion1);

        tabRegion2.setLayout(new java.awt.GridLayout(4, 2));

        //try {
            //    GraphModel model = new models.NIRS.NIRSGraphModelA();
            //    tabRegion2.add(new SeriesChartPane(model));
            //}
        //catch (FileNotFoundException e) {
            //    System.out.println("oh no");
            //}

        jTabbedPane1.addTab("Region 2", tabRegion2);

        javax.swing.GroupLayout tabRegion3Layout = new javax.swing.GroupLayout(tabRegion3);
        tabRegion3.setLayout(tabRegion3Layout);
        tabRegion3Layout.setHorizontalGroup(
            tabRegion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        tabRegion3Layout.setVerticalGroup(
            tabRegion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Region 3", tabRegion3);

        javax.swing.GroupLayout tabRegion4Layout = new javax.swing.GroupLayout(tabRegion4);
        tabRegion4.setLayout(tabRegion4Layout);
        tabRegion4Layout.setHorizontalGroup(
            tabRegion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        tabRegion4Layout.setVerticalGroup(
            tabRegion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Region 4", tabRegion4);

        javax.swing.GroupLayout tabRegion5Layout = new javax.swing.GroupLayout(tabRegion5);
        tabRegion5.setLayout(tabRegion5Layout);
        tabRegion5Layout.setHorizontalGroup(
            tabRegion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        tabRegion5Layout.setVerticalGroup(
            tabRegion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Region 5", tabRegion5);

        javax.swing.GroupLayout tabRegion6Layout = new javax.swing.GroupLayout(tabRegion6);
        tabRegion6.setLayout(tabRegion6Layout);
        tabRegion6Layout.setHorizontalGroup(
            tabRegion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        tabRegion6Layout.setVerticalGroup(
            tabRegion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Region 6", tabRegion6);

        javax.swing.GroupLayout tabRegion7Layout = new javax.swing.GroupLayout(tabRegion7);
        tabRegion7.setLayout(tabRegion7Layout);
        tabRegion7Layout.setHorizontalGroup(
            tabRegion7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        tabRegion7Layout.setVerticalGroup(
            tabRegion7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Region 7", tabRegion7);

        javax.swing.GroupLayout tabRegion8Layout = new javax.swing.GroupLayout(tabRegion8);
        tabRegion8.setLayout(tabRegion8Layout);
        tabRegion8Layout.setHorizontalGroup(
            tabRegion8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        tabRegion8Layout.setVerticalGroup(
            tabRegion8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Region 8", tabRegion8);

        file.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        file.add(open);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setText("Save As ...");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        file.add(save);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        edit.setText("Edit");
        edit.add(NIRSTester);
        
        NIRSTester.setText("Test NIRS Region");
        NIRSTester.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		try {
					cont.changeBrainRegion();
				} catch (ParseException e) {
					e.printStackTrace();
				}
        	}
        });
        
        jMenuBar1.add(edit);

        navi.setText("Navigate");

        back.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        navi.add(back);

        forward.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.ALT_MASK));
        forward.setText("Forward");
        forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardActionPerformed(evt);
            }
        });
        navi.add(forward);

        home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        navi.add(home);

        jMenuBar1.add(navi);

        actions.setText("Actions");

        start.setText("Start Recording");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        actions.add(start);

        stop.setText("Stop Recording");
        stop.setEnabled(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        actions.add(stop);

        jMenuBar1.add(actions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        JFileChooser fcSave = new JFileChooser();
        int rVal = fcSave.showSaveDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            // Save the file to directory
        }
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if(stop.isEnabled())
            cont.stopRecording();
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int index = jTabbedPane1.getSelectedIndex() - 1;
        if(index == - 1)
            jTabbedPane1.setSelectedIndex(Global.MAX_TABS - 1);
        else
            jTabbedPane1.setSelectedIndex(index);
    }//GEN-LAST:event_backActionPerformed

    private void forwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardActionPerformed
        // TODO add your handling code here:
        int index = jTabbedPane1.getSelectedIndex() + 1;
        if(index >= Global.MAX_TABS)
            jTabbedPane1.setSelectedIndex(0);
        else
            jTabbedPane1.setSelectedIndex(index);
    }//GEN-LAST:event_forwardActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_homeActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        if(cont.startRecording()) {
            stop.setEnabled(true);
            start.setEnabled(false);
        }
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        if(cont.stopRecording()) {
            stop.setEnabled(false);
            start.setEnabled(true);
        }
    }//GEN-LAST:event_stopActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(stop.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Closing open patient file...");
            cont.stopRecording();
        }
    }//GEN-LAST:event_formWindowClosing

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        JFileChooser fcOpen = new JFileChooser();
        int rVal = fcOpen.showOpenDialog(this);
        if(rVal == JFileChooser.APPROVE_OPTION) {
            // Open file with the name
        }
    }//GEN-LAST:event_openActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actions;
    private javax.swing.JMenuItem back;
    private javax.swing.JMenu edit;
    private javax.swing.JMenuItem NIRSTester;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem forward;
    private javax.swing.JMenuItem home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel leftEEG;
    private javax.swing.JPanel leftMain;
    private javax.swing.JMenu navi;
    private javax.swing.JMenuItem open;
    private javax.swing.JPanel rightEEG;
    private javax.swing.JPanel rightMain;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem start;
    private javax.swing.JMenuItem stop;
    private javax.swing.JPanel tabBrain;
    private javax.swing.JPanel tabEEG;
    private javax.swing.JPanel tabRegion1;
    private javax.swing.JPanel tabRegion2;
    private javax.swing.JPanel tabRegion3;
    private javax.swing.JPanel tabRegion4;
    private javax.swing.JPanel tabRegion5;
    private javax.swing.JPanel tabRegion6;
    private javax.swing.JPanel tabRegion7;
    private javax.swing.JPanel tabRegion8;
    // End of variables declaration//GEN-END:variables
}
