/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.Controller;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import tools.Global;
import interfaces.GraphModel;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.BrainOverlay;
import models.NIRS.DefaultGraphModel;
import models.SeriesChartPane;
import tools.ImageMap;


/**
 *
 * @author thy
 */
public class View extends javax.swing.JFrame {
    static Controller cont = new Controller();
    /**
     * Creates new form view
     */
    public View() {
        initComponents();
        cont.startRecording();
        start.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabBrain = new javax.swing.JPanel();
        leftMain = new javax.swing.JPanel();
        leftMainLabel = new javax.swing.JLabel();
        leftMainLabel2 = new javax.swing.JLabel();
        rightMain = new javax.swing.JPanel();
        tabEEG = new javax.swing.JPanel();
        leftEEG = new javax.swing.JPanel();
        rightEEG = new javax.swing.JPanel();
        tabRegion1 = new javax.swing.JPanel();
        tabRegion2 = new javax.swing.JPanel();
        tabRegion3 = new javax.swing.JPanel();
        tabRegion4 = new javax.swing.JPanel();
        tabRegion5 = new javax.swing.JPanel();
        tabRegion6 = new javax.swing.JPanel();
        tabRegion7 = new javax.swing.JPanel();
        tabRegion8 = new javax.swing.JPanel();
        tabRegion9 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        NIRSTester = new javax.swing.JMenuItem();
        navi = new javax.swing.JMenu();
        back = new javax.swing.JMenuItem();
        forward = new javax.swing.JMenuItem();
        home = new javax.swing.JMenuItem();
        actions = new javax.swing.JMenu();
        start = new javax.swing.JMenuItem();
        stop = new javax.swing.JMenuItem();
        // NIRS REGION 1
         N1_jPanel1 = new javax.swing.JPanel();
         N1_jLabel1 = new javax.swing.JLabel();
         N1_jPanel2 = new javax.swing.JPanel();
         N1_jLabel2 = new javax.swing.JLabel();
         N1_jPanel3 = new javax.swing.JPanel();
         N1_jLabel3 = new javax.swing.JLabel();
         N1_jPanel4 = new javax.swing.JPanel();
         N1_jLabel4 = new javax.swing.JLabel();
         N1_jPanel5 = new javax.swing.JPanel();
         N1_jLabel5 = new javax.swing.JLabel();
         N1_jPanel6 = new javax.swing.JPanel();
         N1_jLabel6 = new javax.swing.JLabel();

         // NIRS REGION 2
         N2_jPanel1 = new javax.swing.JPanel();
         N2_jLabel1 = new javax.swing.JLabel();
         N2_jPanel2 = new javax.swing.JPanel();
         N2_jLabel2 = new javax.swing.JLabel();
         N2_jPanel3 = new javax.swing.JPanel();
         N2_jLabel3 = new javax.swing.JLabel();
         N2_jPanel4 = new javax.swing.JPanel();
         N2_jLabel4 = new javax.swing.JLabel();
         N2_jPanel5 = new javax.swing.JPanel();
         N2_jLabel5 = new javax.swing.JLabel();
         N2_jPanel6 = new javax.swing.JPanel();
         N2_jLabel6 = new javax.swing.JLabel();

         // NIRS REGION 3
         N3_jPanel1 = new javax.swing.JPanel();
         N3_jLabel1 = new javax.swing.JLabel();
         N3_jPanel2 = new javax.swing.JPanel();
         N3_jLabel2 = new javax.swing.JLabel();
         N3_jPanel3 = new javax.swing.JPanel();
         N3_jLabel3 = new javax.swing.JLabel();
         N3_jPanel4 = new javax.swing.JPanel();
         N3_jLabel4 = new javax.swing.JLabel();
         N3_jPanel5 = new javax.swing.JPanel();
         N3_jLabel5 = new javax.swing.JLabel();
         N3_jPanel6 = new javax.swing.JPanel();
         N3_jLabel6 = new javax.swing.JLabel();

         // NIRS REGION 4
         N4_jPanel1 = new javax.swing.JPanel();
         N4_jLabel1 = new javax.swing.JLabel();
         N4_jPanel2 = new javax.swing.JPanel();
         N4_jLabel2 = new javax.swing.JLabel();
         N4_jPanel3 = new javax.swing.JPanel();
         N4_jLabel3 = new javax.swing.JLabel();
         N4_jPanel4 = new javax.swing.JPanel();
         N4_jLabel4 = new javax.swing.JLabel();
         N4_jPanel5 = new javax.swing.JPanel();
         N4_jLabel5 = new javax.swing.JLabel();
         N4_jPanel6 = new javax.swing.JPanel();
         N4_jLabel6 = new javax.swing.JLabel();

         // NIRS REGION 5
         N5_jPanel1 = new javax.swing.JPanel();
         N5_jLabel1 = new javax.swing.JLabel();
         N5_jPanel2 = new javax.swing.JPanel();
         N5_jLabel2 = new javax.swing.JLabel();
         N5_jPanel3 = new javax.swing.JPanel();
         N5_jLabel3 = new javax.swing.JLabel();
         N5_jPanel4 = new javax.swing.JPanel();
         N5_jLabel4 = new javax.swing.JLabel();
         N5_jPanel5 = new javax.swing.JPanel();
         N5_jLabel5 = new javax.swing.JLabel();
         N5_jPanel6 = new javax.swing.JPanel();
         N5_jLabel6 = new javax.swing.JLabel();

         // NIRS REGION 6
         N6_jPanel1 = new javax.swing.JPanel();
         N6_jLabel1 = new javax.swing.JLabel();
         N6_jPanel2 = new javax.swing.JPanel();
         N6_jLabel2 = new javax.swing.JLabel();
         N6_jPanel3 = new javax.swing.JPanel();
         N6_jLabel3 = new javax.swing.JLabel();
         N6_jPanel4 = new javax.swing.JPanel();
         N6_jLabel4 = new javax.swing.JLabel();
         N6_jPanel5 = new javax.swing.JPanel();
         N6_jLabel5 = new javax.swing.JLabel();
         N6_jPanel6 = new javax.swing.JPanel();
         N6_jLabel6 = new javax.swing.JLabel();

         // NIRS REGION 7
         N7_jPanel1 = new javax.swing.JPanel();
         N7_jLabel1 = new javax.swing.JLabel();
         N7_jPanel2 = new javax.swing.JPanel();
         N7_jLabel2 = new javax.swing.JLabel();
         N7_jPanel3 = new javax.swing.JPanel();
         N7_jLabel3 = new javax.swing.JLabel();
         N7_jPanel4 = new javax.swing.JPanel();
         N7_jLabel4 = new javax.swing.JLabel();
         N7_jPanel5 = new javax.swing.JPanel();
         N7_jLabel5 = new javax.swing.JLabel();
         N7_jPanel6 = new javax.swing.JPanel();
         N7_jLabel6 = new javax.swing.JLabel();

         // NIRS REGION 8
         N8_jPanel1 = new javax.swing.JPanel();
         N8_jLabel1 = new javax.swing.JLabel();
         N8_jPanel2 = new javax.swing.JPanel();
         N8_jLabel2 = new javax.swing.JLabel();
         N8_jPanel3 = new javax.swing.JPanel();
         N8_jLabel3 = new javax.swing.JLabel();
         N8_jPanel4 = new javax.swing.JPanel();
         N8_jLabel4 = new javax.swing.JLabel();
         N8_jPanel5 = new javax.swing.JPanel();
         N8_jLabel5 = new javax.swing.JLabel();
         N8_jPanel6 = new javax.swing.JPanel();
         N8_jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multimodal Neural Monitoring");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        tabBrain.setLayout(new javax.swing.BoxLayout(tabBrain, javax.swing.BoxLayout.LINE_AXIS));

        leftMain.setBorder(BorderFactory.createTitledBorder(""));
        leftMain.setLayout(new java.awt.GridLayout(3,1));

        try {
            GraphModel mainModel = new models.NIRS.NIRSGraphModelA();
            leftMain.add(new SeriesChartPane(mainModel));
        }
        catch(Exception e) {
            e.printStackTrace();
        }

        leftMainLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        leftMainLabel.setText("Global Oxygenation:");
        leftMain.add(leftMainLabel);

        leftMainLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        leftMainLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftMainLabel2.setText(cont.getGlobalOxygenation() + "%");
        leftMain.add(leftMainLabel2);

        tabBrain.add(leftMain);

        rightMain.setLayout(new java.awt.GridBagLayout());
        rightMain.setBorder(BorderFactory.createTitledBorder(""));

        cont.implementRegionImages(rightMain, jTabbedPane1);

        tabBrain.add(rightMain);

        jTabbedPane1.addTab("Main", tabBrain);

        tabEEG.setLayout(new java.awt.GridBagLayout());

        leftEEG.setBorder(BorderFactory.createTitledBorder(""));
        leftEEG.setLayout(new java.awt.GridLayout(2, 2));

//        javax.swing.GroupLayout leftEEGLayout = new javax.swing.GroupLayout(leftEEG);
//        leftEEG.setLayout(leftEEGLayout);
//        leftEEGLayout.setHorizontalGroup(
//            leftEEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 529, Short.MAX_VALUE)
//        );
//        leftEEGLayout.setVerticalGroup(
//            leftEEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 460, Short.MAX_VALUE)
//        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            leftEEG.add(new SeriesChartPane(model));
            leftEEG.add(new SeriesChartPane(model));
            leftEEG.add(new SeriesChartPane(model));
            leftEEG.add(new SeriesChartPane(model));
        }
        catch(Exception e) {
            e.printStackTrace();
        }

        tabEEG.add(leftEEG, new java.awt.GridBagConstraints());

        rightEEG.setLayout(new java.awt.GridLayout(4, 2));
        rightEEG.setBorder(BorderFactory.createTitledBorder(""));

        try {
            BufferedImage eeg = ImageIO.read(new File("src/images/updated_eeg_map.png"));

            ArrayList<BufferedImage> abiRegions = new ArrayList<BufferedImage>();
            ArrayList<ImageIcon> aiRegions = new ArrayList<ImageIcon>();
            ArrayList<JLabel> ajlRegions = new ArrayList<JLabel>();
            ImageMap imageSlice = new ImageMap(eeg, abiRegions, aiRegions, ajlRegions);
            for(int i = 0; i < ajlRegions.size(); i++) {
                rightEEG.add(ajlRegions.get(i));
            }
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        tabEEG.add(rightEEG, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("EEG", tabEEG);

        // BEGIN NIRS REGION 1

        tabRegion1.setLayout(new java.awt.GridLayout(2,2));

        N1_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N1_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N1_jLabel1.setText("Status:");

        N1_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N1_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N1_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N1_jLabel2.setText("Good");

        javax.swing.GroupLayout N1_jPanel1Layout = new javax.swing.GroupLayout(N1_jPanel1);
        N1_jPanel1.setLayout(N1_jPanel1Layout);
        N1_jPanel1Layout.setHorizontalGroup(
            N1_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N1_jPanel1Layout.createSequentialGroup()
                .addComponent(N1_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N1_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N1_jPanel1Layout.setVerticalGroup(
            N1_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N1_jPanel1Layout.createSequentialGroup()
                .addComponent(N1_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N1_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion1.add(N1_jPanel1);

        N1_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N1_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N1_jLabel3.setText("Oxygenation:");

        N1_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N1_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N1_jLabel4.setText("78%");

        N1_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N1_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N1_jPanel2Layout = new javax.swing.GroupLayout(N1_jPanel2);
        N1_jPanel2.setLayout(N1_jPanel2Layout);
        N1_jPanel2Layout.setHorizontalGroup(
            N1_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N1_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N1_jPanel2Layout.createSequentialGroup()
                .addComponent(N1_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N1_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N1_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N1_jPanel2Layout.setVerticalGroup(
            N1_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N1_jPanel2Layout.createSequentialGroup()
                .addComponent(N1_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N1_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N1_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N1_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion1.add(N1_jPanel2);

        N1_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N1_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N1_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N1_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N1_jPanel3Layout = new javax.swing.GroupLayout(N1_jPanel3);
        N1_jPanel3.setLayout(N1_jPanel3Layout);
        N1_jPanel3Layout.setHorizontalGroup(
            N1_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N1_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N1_jPanel3Layout.setVerticalGroup(
            N1_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N1_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion1.add(N1_jPanel3);

        N1_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N1_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N1_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N1_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N1_jPanel4Layout = new javax.swing.GroupLayout(N1_jPanel4);
        N1_jPanel4.setLayout(N1_jPanel4Layout);
        N1_jPanel4Layout.setHorizontalGroup(
            N1_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N1_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N1_jPanel4Layout.setVerticalGroup(
            N1_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N1_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion1.add(N1_jPanel4);
        jTabbedPane1.addTab("Region 1", tabRegion1);

        // END NIRS REGION 1

        // BEGIN NIRS REGION 2

        tabRegion2.setLayout(new java.awt.GridLayout(2,2));
        N2_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N2_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N2_jLabel1.setText("Status:");

        N2_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N2_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N2_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N2_jLabel2.setText("Good");

        javax.swing.GroupLayout N2_jPanel1Layout = new javax.swing.GroupLayout(N2_jPanel1);
        N2_jPanel1.setLayout(N2_jPanel1Layout);
        N2_jPanel1Layout.setHorizontalGroup(
            N2_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N2_jPanel1Layout.createSequentialGroup()
                .addComponent(N2_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N2_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N2_jPanel1Layout.setVerticalGroup(
            N2_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N2_jPanel1Layout.createSequentialGroup()
                .addComponent(N2_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N2_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion2.add(N2_jPanel1);

        N2_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N2_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N2_jLabel3.setText("Oxygenation:");

        N2_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N2_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N2_jLabel4.setText("78%");

        N2_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N2_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N2_jPanel2Layout = new javax.swing.GroupLayout(N2_jPanel2);
        N2_jPanel2.setLayout(N2_jPanel2Layout);
        N2_jPanel2Layout.setHorizontalGroup(
            N2_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N2_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N2_jPanel2Layout.createSequentialGroup()
                .addComponent(N2_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N2_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N2_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N2_jPanel2Layout.setVerticalGroup(
            N2_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N2_jPanel2Layout.createSequentialGroup()
                .addComponent(N2_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N2_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N2_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N2_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion2.add(N2_jPanel2);

        N2_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N2_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N2_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N2_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N2_jPanel3Layout = new javax.swing.GroupLayout(N2_jPanel3);
        N2_jPanel3.setLayout(N2_jPanel3Layout);
        N2_jPanel3Layout.setHorizontalGroup(
            N2_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N2_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N2_jPanel3Layout.setVerticalGroup(
            N2_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N2_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion2.add(N2_jPanel3);

        N2_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N2_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N2_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N2_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N2_jPanel4Layout = new javax.swing.GroupLayout(N2_jPanel4);
        N2_jPanel4.setLayout(N2_jPanel4Layout);
        N2_jPanel4Layout.setHorizontalGroup(
            N2_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N2_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N2_jPanel4Layout.setVerticalGroup(
            N2_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N2_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion2.add(N2_jPanel4);

        jTabbedPane1.addTab("Region 2", tabRegion2);

        // END NIRS REGION 2

        // BEGIN NIRS REGION 3

        tabRegion3.setLayout(new java.awt.GridLayout(2,2));
        N3_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N3_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N3_jLabel1.setText("Status:");

        N3_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N3_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N3_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N3_jLabel2.setText("Good");

        javax.swing.GroupLayout N3_jPanel1Layout = new javax.swing.GroupLayout(N3_jPanel1);
        N3_jPanel1.setLayout(N3_jPanel1Layout);
        N3_jPanel1Layout.setHorizontalGroup(
            N3_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N3_jPanel1Layout.createSequentialGroup()
                .addComponent(N3_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N3_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N3_jPanel1Layout.setVerticalGroup(
            N3_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N3_jPanel1Layout.createSequentialGroup()
                .addComponent(N3_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N3_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion3.add(N3_jPanel1);

        N3_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N3_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N3_jLabel3.setText("Oxygenation:");

        N3_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N3_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N3_jLabel4.setText("78%");

        N3_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N3_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N3_jPanel2Layout = new javax.swing.GroupLayout(N3_jPanel2);
        N3_jPanel2.setLayout(N3_jPanel2Layout);
        N3_jPanel2Layout.setHorizontalGroup(
            N3_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N3_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N3_jPanel2Layout.createSequentialGroup()
                .addComponent(N3_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N3_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N3_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N3_jPanel2Layout.setVerticalGroup(
            N3_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N3_jPanel2Layout.createSequentialGroup()
                .addComponent(N3_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N3_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N3_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N3_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion3.add(N3_jPanel2);

        N3_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N3_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N3_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N3_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N3_jPanel3Layout = new javax.swing.GroupLayout(N3_jPanel3);
        N3_jPanel3.setLayout(N3_jPanel3Layout);
        N3_jPanel3Layout.setHorizontalGroup(
            N3_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N3_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N3_jPanel3Layout.setVerticalGroup(
            N3_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N3_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion3.add(N3_jPanel3);

        N3_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N3_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N3_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N3_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N3_jPanel4Layout = new javax.swing.GroupLayout(N3_jPanel4);
        N3_jPanel4.setLayout(N3_jPanel4Layout);
        N3_jPanel4Layout.setHorizontalGroup(
            N3_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N3_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N3_jPanel4Layout.setVerticalGroup(
            N3_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N3_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion3.add(N3_jPanel4);

        jTabbedPane1.addTab("Region 3", tabRegion3);

        // END NIRS REGION 3

        // BEGIN NIRS REGION 4

        tabRegion4.setLayout(new java.awt.GridLayout(2,2));
        N4_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N4_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N4_jLabel1.setText("Status:");

        N4_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N4_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N4_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N4_jLabel2.setText("Good");

        javax.swing.GroupLayout N4_jPanel1Layout = new javax.swing.GroupLayout(N4_jPanel1);
        N4_jPanel1.setLayout(N4_jPanel1Layout);
        N4_jPanel1Layout.setHorizontalGroup(
            N4_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N4_jPanel1Layout.createSequentialGroup()
                .addComponent(N4_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N4_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N4_jPanel1Layout.setVerticalGroup(
            N4_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N4_jPanel1Layout.createSequentialGroup()
                .addComponent(N4_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N4_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion4.add(N4_jPanel1);

        N4_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N4_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N4_jLabel3.setText("Oxygenation:");

        N4_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N4_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N4_jLabel4.setText("78%");

        N4_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N4_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N4_jPanel2Layout = new javax.swing.GroupLayout(N4_jPanel2);
        N4_jPanel2.setLayout(N4_jPanel2Layout);
        N4_jPanel2Layout.setHorizontalGroup(
            N4_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N4_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N4_jPanel2Layout.createSequentialGroup()
                .addComponent(N4_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N4_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N4_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N4_jPanel2Layout.setVerticalGroup(
            N4_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N4_jPanel2Layout.createSequentialGroup()
                .addComponent(N4_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N4_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N4_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N4_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion4.add(N4_jPanel2);

        N4_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N4_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N4_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N4_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N4_jPanel3Layout = new javax.swing.GroupLayout(N4_jPanel3);
        N4_jPanel3.setLayout(N4_jPanel3Layout);
        N4_jPanel3Layout.setHorizontalGroup(
            N4_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N4_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N4_jPanel3Layout.setVerticalGroup(
            N4_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N4_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion4.add(N4_jPanel3);

        N4_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N4_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N4_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N4_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N4_jPanel4Layout = new javax.swing.GroupLayout(N4_jPanel4);
        N4_jPanel4.setLayout(N4_jPanel4Layout);
        N4_jPanel4Layout.setHorizontalGroup(
            N4_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N4_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N4_jPanel4Layout.setVerticalGroup(
            N4_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N4_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion4.add(N4_jPanel4);

        jTabbedPane1.addTab("Region 4", tabRegion4);

        // END NIRS REGION 4

        // BEGIN NIRS REGION 5

        tabRegion5.setLayout(new java.awt.GridLayout(2,2));
        N5_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N5_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N5_jLabel1.setText("Status:");

        N5_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N5_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N5_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N5_jLabel2.setText("Good");

        javax.swing.GroupLayout N5_jPanel1Layout = new javax.swing.GroupLayout(N5_jPanel1);
        N5_jPanel1.setLayout(N5_jPanel1Layout);
        N5_jPanel1Layout.setHorizontalGroup(
            N5_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N5_jPanel1Layout.createSequentialGroup()
                .addComponent(N5_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N5_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N5_jPanel1Layout.setVerticalGroup(
            N5_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N5_jPanel1Layout.createSequentialGroup()
                .addComponent(N5_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N5_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion5.add(N5_jPanel1);

        N5_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N5_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N5_jLabel3.setText("Oxygenation:");

        N5_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N5_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N5_jLabel4.setText("78%");

        N5_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N5_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N5_jPanel2Layout = new javax.swing.GroupLayout(N5_jPanel2);
        N5_jPanel2.setLayout(N5_jPanel2Layout);
        N5_jPanel2Layout.setHorizontalGroup(
            N5_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N5_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N5_jPanel2Layout.createSequentialGroup()
                .addComponent(N5_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N5_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N5_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N5_jPanel2Layout.setVerticalGroup(
            N5_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N5_jPanel2Layout.createSequentialGroup()
                .addComponent(N5_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N5_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N5_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N5_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion5.add(N5_jPanel2);

        N5_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N5_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N5_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N5_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N5_jPanel3Layout = new javax.swing.GroupLayout(N5_jPanel3);
        N5_jPanel3.setLayout(N5_jPanel3Layout);
        N5_jPanel3Layout.setHorizontalGroup(
            N5_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N5_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N5_jPanel3Layout.setVerticalGroup(
            N5_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N5_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion5.add(N5_jPanel3);

        N5_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N5_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N5_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N5_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N5_jPanel4Layout = new javax.swing.GroupLayout(N5_jPanel4);
        N5_jPanel4.setLayout(N5_jPanel4Layout);
        N5_jPanel4Layout.setHorizontalGroup(
            N5_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N5_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N5_jPanel4Layout.setVerticalGroup(
            N5_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N5_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion5.add(N5_jPanel4);

        jTabbedPane1.addTab("Region 5", tabRegion5);

        // END NIRS REGION 5

        // BEGIN NIRS REGION 6

        tabRegion6.setLayout(new java.awt.GridLayout(2,2));
        N6_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N6_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N6_jLabel1.setText("Status:");

        N6_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N6_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N6_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N6_jLabel2.setText("Good");

        javax.swing.GroupLayout N6_jPanel1Layout = new javax.swing.GroupLayout(N6_jPanel1);
        N6_jPanel1.setLayout(N6_jPanel1Layout);
        N6_jPanel1Layout.setHorizontalGroup(
            N6_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N6_jPanel1Layout.createSequentialGroup()
                .addComponent(N6_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N6_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N6_jPanel1Layout.setVerticalGroup(
            N6_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N6_jPanel1Layout.createSequentialGroup()
                .addComponent(N6_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N6_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion6.add(N6_jPanel1);

        N6_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N6_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N6_jLabel3.setText("Oxygenation:");

        N6_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N6_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N6_jLabel4.setText("78%");

        N6_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N6_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N6_jPanel2Layout = new javax.swing.GroupLayout(N6_jPanel2);
        N6_jPanel2.setLayout(N6_jPanel2Layout);
        N6_jPanel2Layout.setHorizontalGroup(
            N6_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N6_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N6_jPanel2Layout.createSequentialGroup()
                .addComponent(N6_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N6_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N6_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N6_jPanel2Layout.setVerticalGroup(
            N6_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N6_jPanel2Layout.createSequentialGroup()
                .addComponent(N6_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N6_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N6_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N6_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion6.add(N6_jPanel2);

        N6_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N6_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N6_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N6_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N6_jPanel3Layout = new javax.swing.GroupLayout(N6_jPanel3);
        N6_jPanel3.setLayout(N6_jPanel3Layout);
        N6_jPanel3Layout.setHorizontalGroup(
            N6_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N6_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N6_jPanel3Layout.setVerticalGroup(
            N6_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N6_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion6.add(N6_jPanel3);

        N6_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N6_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N6_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N6_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N6_jPanel4Layout = new javax.swing.GroupLayout(N6_jPanel4);
        N6_jPanel4.setLayout(N6_jPanel4Layout);
        N6_jPanel4Layout.setHorizontalGroup(
            N6_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N6_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N6_jPanel4Layout.setVerticalGroup(
            N6_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N6_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion6.add(N6_jPanel4);

        jTabbedPane1.addTab("Region 6", tabRegion6);

        // END NIRS REGION 6

        // BEGIN NIRS REGION 7

        tabRegion7.setLayout(new java.awt.GridLayout(2,2));
        N7_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N7_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N7_jLabel1.setText("Status:");

        N7_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N7_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N7_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N7_jLabel2.setText("Good");

        javax.swing.GroupLayout N7_jPanel1Layout = new javax.swing.GroupLayout(N7_jPanel1);
        N7_jPanel1.setLayout(N7_jPanel1Layout);
        N7_jPanel1Layout.setHorizontalGroup(
            N7_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N7_jPanel1Layout.createSequentialGroup()
                .addComponent(N7_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N7_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N7_jPanel1Layout.setVerticalGroup(
            N7_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N7_jPanel1Layout.createSequentialGroup()
                .addComponent(N7_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N7_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion7.add(N7_jPanel1);

        N7_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N7_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N7_jLabel3.setText("Oxygenation:");

        N7_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N7_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N7_jLabel4.setText("78%");

        N7_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N7_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N7_jPanel2Layout = new javax.swing.GroupLayout(N7_jPanel2);
        N7_jPanel2.setLayout(N7_jPanel2Layout);
        N7_jPanel2Layout.setHorizontalGroup(
            N7_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N7_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N7_jPanel2Layout.createSequentialGroup()
                .addComponent(N7_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N7_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N7_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N7_jPanel2Layout.setVerticalGroup(
            N7_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N7_jPanel2Layout.createSequentialGroup()
                .addComponent(N7_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N7_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N7_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N7_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion7.add(N7_jPanel2);

        N7_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N7_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N7_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N7_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N7_jPanel3Layout = new javax.swing.GroupLayout(N7_jPanel3);
        N7_jPanel3.setLayout(N7_jPanel3Layout);
        N7_jPanel3Layout.setHorizontalGroup(
            N7_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N7_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N7_jPanel3Layout.setVerticalGroup(
            N7_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N7_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion7.add(N7_jPanel3);

        N7_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N7_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N7_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N7_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N7_jPanel4Layout = new javax.swing.GroupLayout(N7_jPanel4);
        N7_jPanel4.setLayout(N7_jPanel4Layout);
        N7_jPanel4Layout.setHorizontalGroup(
            N7_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N7_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N7_jPanel4Layout.setVerticalGroup(
            N7_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N7_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion7.add(N7_jPanel4);

        jTabbedPane1.addTab("Region 7", tabRegion7);

        // END NIRS REGION 7

        // BEGIN NIRS REGION 8

        tabRegion8.setLayout(new java.awt.GridLayout(2,2));
        N8_jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N8_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N8_jLabel1.setText("Status:");

        N8_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        N8_jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        N8_jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N8_jLabel2.setText("Good");

        javax.swing.GroupLayout N8_jPanel1Layout = new javax.swing.GroupLayout(N8_jPanel1);
        N8_jPanel1.setLayout(N8_jPanel1Layout);
        N8_jPanel1Layout.setHorizontalGroup(
            N8_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N8_jPanel1Layout.createSequentialGroup()
                .addComponent(N8_jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(N8_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N8_jPanel1Layout.setVerticalGroup(
            N8_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N8_jPanel1Layout.createSequentialGroup()
                .addComponent(N8_jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N8_jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        tabRegion8.add(N8_jPanel1);

        N8_jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N8_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        N8_jLabel3.setText("Oxygenation:");

        N8_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        N8_jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N8_jLabel4.setText("78%");

        N8_jPanel5.setLayout(new java.awt.GridLayout());

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N8_jPanel5.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        javax.swing.GroupLayout N8_jPanel2Layout = new javax.swing.GroupLayout(N8_jPanel2);
        N8_jPanel2.setLayout(N8_jPanel2Layout);
        N8_jPanel2Layout.setHorizontalGroup(
            N8_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N8_jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(N8_jPanel2Layout.createSequentialGroup()
                .addComponent(N8_jLabel3)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, N8_jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(N8_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        N8_jPanel2Layout.setVerticalGroup(
            N8_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(N8_jPanel2Layout.createSequentialGroup()
                .addComponent(N8_jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N8_jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N8_jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        try {
            GraphModel model = new models.NIRS.NIRSGraphModelA();
            N8_jPanel2.add(new SeriesChartPane(model));
        }
        catch (FileNotFoundException e) {
            System.out.println("oh no");
        }

        tabRegion8.add(N8_jPanel2);

        N8_jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N8_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N8_jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N8_jLabel5.setText("Blood Flow");

        javax.swing.GroupLayout N8_jPanel3Layout = new javax.swing.GroupLayout(N8_jPanel3);
        N8_jPanel3.setLayout(N8_jPanel3Layout);
        N8_jPanel3Layout.setHorizontalGroup(
            N8_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N8_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N8_jPanel3Layout.setVerticalGroup(
            N8_jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N8_jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion8.add(N8_jPanel3);

        N8_jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        N8_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        N8_jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        N8_jLabel6.setText("Temperature");

        javax.swing.GroupLayout N8_jPanel4Layout = new javax.swing.GroupLayout(N8_jPanel4);
        N8_jPanel4.setLayout(N8_jPanel4Layout);
        N8_jPanel4Layout.setHorizontalGroup(
            N8_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N8_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        N8_jPanel4Layout.setVerticalGroup(
            N8_jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(N8_jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );

        tabRegion8.add(N8_jPanel4);

        jTabbedPane1.addTab("Region 8", tabRegion8);

        // END NIRS REGION 8

        // BEGIN EE TESTING TAB

        tabRegion9.add(new JLabel("testing"));
        jTabbedPane1.addTab("EE Test", tabRegion9);

        // END EE TESTING TAB

        file.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        file.add(open);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setText("Save As ...");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        file.add(save);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        jMenuBar1.add(file);

        edit.setText("Edit");
        jMenuBar1.add(edit);

        NIRSTester.setText("Test NIRS Region");
        NIRSTester.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		try {
					cont.changeBrainRegion();
				} catch (ParseException e) {
					e.printStackTrace();
				}
        	}
        });

        edit.add(NIRSTester);

        navi.setText("Navigate");

        back.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        navi.add(back);

        forward.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.ALT_MASK));
        forward.setText("Forward");
        forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardActionPerformed(evt);
            }
        });
        navi.add(forward);

        home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        navi.add(home);

        jMenuBar1.add(navi);

        actions.setText("Actions");

        start.setText("Start Recording");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        actions.add(start);

        stop.setText("Stop Recording");
        stop.setEnabled(false);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        actions.add(stop);

        jMenuBar1.add(actions);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void updateOxygenation() {
      leftMainLabel2.setText(cont.globalOxygenation + "%");
   }

    public static void updateRegion() {
        int round = (int) (100 * cont.oxygenation.get(cont.region));

      if(cont.region == 0) {
         N1_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N1_jLabel2.setForeground(Color.YELLOW);
            N1_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N1_jLabel2.setForeground(Color.RED);
            N1_jLabel2.setText("Critical");
         }
         else {
            N1_jLabel2.setForeground(Color.GREEN);
            N1_jLabel2.setText("Good");
         }
      }
      else if(cont.region == 1) {
         N2_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N2_jLabel2.setForeground(Color.YELLOW);
            N2_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N2_jLabel2.setForeground(Color.RED);
            N2_jLabel2.setText("Critical");
         }
         else {
            N2_jLabel2.setForeground(Color.GREEN);
            N2_jLabel2.setText("Good");
         }
      }
      else if(cont.region == 2) {
         N3_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N3_jLabel2.setForeground(Color.YELLOW);
            N3_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N3_jLabel2.setForeground(Color.RED);
            N3_jLabel2.setText("Critical");
         }
         else {
            N3_jLabel2.setForeground(Color.GREEN);
            N3_jLabel2.setText("Good");
         }
      }
      else if(cont.region == 3) {
         N4_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N4_jLabel2.setForeground(Color.YELLOW);
            N4_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N4_jLabel2.setForeground(Color.RED);
            N4_jLabel2.setText("Critical");
         }
         else {
            N4_jLabel2.setForeground(Color.GREEN);
            N4_jLabel2.setText("Good");
         }
      }
      else if(cont.region == 4) {
         N5_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N5_jLabel2.setForeground(Color.YELLOW);
            N5_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N5_jLabel2.setForeground(Color.RED);
            N5_jLabel2.setText("Critical");
         }
         else {
            N5_jLabel2.setForeground(Color.GREEN);
            N5_jLabel2.setText("Good");
         }
      }
      else if(cont.region == 5) {
         N6_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N6_jLabel2.setForeground(Color.YELLOW);
            N6_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N6_jLabel2.setForeground(Color.RED);
            N6_jLabel2.setText("Critical");
         }
         else {
            N6_jLabel2.setForeground(Color.GREEN);
            N6_jLabel2.setText("Good");
         }
      }
      else if(cont.region == 6) {
         N7_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N7_jLabel2.setForeground(Color.YELLOW);
            N7_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N7_jLabel2.setForeground(Color.RED);
            N7_jLabel2.setText("Critical");
         }
         else {
            N7_jLabel2.setForeground(Color.GREEN);
            N7_jLabel2.setText("Good");
         }
      }
      else if(cont.region == 7) {
         N8_jLabel4.setText(round + "%");
         if(cont.color == 1) {
            N8_jLabel2.setForeground(Color.YELLOW);
            N8_jLabel2.setText("Abnormal");
         }
         else if(cont.color == 2) {
            N8_jLabel2.setForeground(Color.RED);
            N8_jLabel2.setText("Critical");
         }
         else {
            N8_jLabel2.setForeground(Color.GREEN);
            N8_jLabel2.setText("Good");
         }
      }
      else {
         System.out.println("yikes");
      }
   }

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        JFileChooser fcSave = new JFileChooser();
        int rVal = fcSave.showSaveDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION) {
            // Save the file to directory
        }
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if(stop.isEnabled())
            cont.stopRecording();
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        int index = jTabbedPane1.getSelectedIndex() - 1;
        if(index == - 1)
            jTabbedPane1.setSelectedIndex(Global.MAX_TABS - 1);
        else
            jTabbedPane1.setSelectedIndex(index);
    }//GEN-LAST:event_backActionPerformed

    private void forwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardActionPerformed
        // TODO add your handling code here:
        int index = jTabbedPane1.getSelectedIndex() + 1;
        if(index >= Global.MAX_TABS)
            jTabbedPane1.setSelectedIndex(0);
        else
            jTabbedPane1.setSelectedIndex(index);
    }//GEN-LAST:event_forwardActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_homeActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        stop.setEnabled(true);
        start.setEnabled(false);
    }//GEN-LAST:event_startActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        if(cont.stopRecording()) {
            stop.setEnabled(false);
            start.setEnabled(true);
        }
    }//GEN-LAST:event_stopActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(stop.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Closing open patient file...");
            cont.stopRecording();
        }
    }//GEN-LAST:event_formWindowClosing

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        JFileChooser fcOpen = new JFileChooser();
        int rVal = fcOpen.showOpenDialog(this);
        if(rVal == JFileChooser.APPROVE_OPTION) {
            // Open file with the name
        }
    }//GEN-LAST:event_openActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actions;
    private javax.swing.JMenuItem back;
    private javax.swing.JMenu edit;
    private javax.swing.JMenuItem NIRSTester;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem forward;
    private javax.swing.JMenuItem home;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel leftEEG;
    private javax.swing.JPanel leftMain;
    private javax.swing.JLabel leftMainLabel;
    private static javax.swing.JLabel leftMainLabel2;
    private javax.swing.JMenu navi;
    private javax.swing.JMenuItem open;
    private javax.swing.JPanel rightEEG;
    private javax.swing.JPanel rightMain;
    private javax.swing.JMenuItem save;
    private javax.swing.JMenuItem start;
    private javax.swing.JMenuItem stop;
    private javax.swing.JPanel tabBrain;
    private javax.swing.JPanel tabEEG;
    private javax.swing.JPanel tabRegion1;
    private javax.swing.JPanel tabRegion2;
    private javax.swing.JPanel tabRegion3;
    private javax.swing.JPanel tabRegion4;
    private javax.swing.JPanel tabRegion5;
    private javax.swing.JPanel tabRegion6;
    private javax.swing.JPanel tabRegion7;
    private javax.swing.JPanel tabRegion8;
    private javax.swing.JPanel tabRegion9;

    // NIRS REGION 1
   private static javax.swing.JPanel N1_jPanel1;
   private static javax.swing.JPanel N1_jPanel2;
   private static javax.swing.JPanel N1_jPanel3;
   private static javax.swing.JPanel N1_jPanel4;
   private static javax.swing.JPanel N1_jPanel5;
   private static javax.swing.JPanel N1_jPanel6;
   private static javax.swing.JLabel N1_jLabel1;
   private static javax.swing.JLabel N1_jLabel2;
   private static javax.swing.JLabel N1_jLabel3;
   private static javax.swing.JLabel N1_jLabel4;
   private static javax.swing.JLabel N1_jLabel5;
   private static javax.swing.JLabel N1_jLabel6;

   // NIRS REGION 2
   private static javax.swing.JPanel N2_jPanel1;
   private static javax.swing.JPanel N2_jPanel2;
   private static javax.swing.JPanel N2_jPanel3;
   private static javax.swing.JPanel N2_jPanel4;
   private static javax.swing.JPanel N2_jPanel5;
   private static javax.swing.JPanel N2_jPanel6;
   private static javax.swing.JLabel N2_jLabel1;
   private static javax.swing.JLabel N2_jLabel2;
   private static javax.swing.JLabel N2_jLabel3;
   private static javax.swing.JLabel N2_jLabel4;
   private static javax.swing.JLabel N2_jLabel5;
   private static javax.swing.JLabel N2_jLabel6;

   // NIRS REGION 3
   private static javax.swing.JPanel N3_jPanel1;
   private static javax.swing.JPanel N3_jPanel2;
   private static javax.swing.JPanel N3_jPanel3;
   private static javax.swing.JPanel N3_jPanel4;
   private static javax.swing.JPanel N3_jPanel5;
   private static javax.swing.JPanel N3_jPanel6;
   private static javax.swing.JLabel N3_jLabel1;
   private static javax.swing.JLabel N3_jLabel2;
   private static javax.swing.JLabel N3_jLabel3;
   private static javax.swing.JLabel N3_jLabel4;
   private static javax.swing.JLabel N3_jLabel5;
   private static javax.swing.JLabel N3_jLabel6;

   // NIRS REGION 4
   private static javax.swing.JPanel N4_jPanel1;
   private static javax.swing.JPanel N4_jPanel2;
   private static javax.swing.JPanel N4_jPanel3;
   private static javax.swing.JPanel N4_jPanel4;
   private static javax.swing.JPanel N4_jPanel5;
   private static javax.swing.JPanel N4_jPanel6;
   private static javax.swing.JLabel N4_jLabel1;
   private static javax.swing.JLabel N4_jLabel2;
   private static javax.swing.JLabel N4_jLabel3;
   private static javax.swing.JLabel N4_jLabel4;
   private static javax.swing.JLabel N4_jLabel5;
   private static javax.swing.JLabel N4_jLabel6;

   // NIRS REGION 5
   private static javax.swing.JPanel N5_jPanel1;
   private static javax.swing.JPanel N5_jPanel2;
   private static javax.swing.JPanel N5_jPanel3;
   private static javax.swing.JPanel N5_jPanel4;
   private static javax.swing.JPanel N5_jPanel5;
   private static javax.swing.JPanel N5_jPanel6;
   private static javax.swing.JLabel N5_jLabel1;
   private static javax.swing.JLabel N5_jLabel2;
   private static javax.swing.JLabel N5_jLabel3;
   private static javax.swing.JLabel N5_jLabel4;
   private static javax.swing.JLabel N5_jLabel5;
   private static javax.swing.JLabel N5_jLabel6;

   // NIRS REGION 6
   private static javax.swing.JPanel N6_jPanel1;
   private static javax.swing.JPanel N6_jPanel2;
   private static javax.swing.JPanel N6_jPanel3;
   private static javax.swing.JPanel N6_jPanel4;
   private static javax.swing.JPanel N6_jPanel5;
   private static javax.swing.JPanel N6_jPanel6;
   private static javax.swing.JLabel N6_jLabel1;
   private static javax.swing.JLabel N6_jLabel2;
   private static javax.swing.JLabel N6_jLabel3;
   private static javax.swing.JLabel N6_jLabel4;
   private static javax.swing.JLabel N6_jLabel5;
   private static javax.swing.JLabel N6_jLabel6;

   // NIRS REGION 7
   private static javax.swing.JPanel N7_jPanel1;
   private static javax.swing.JPanel N7_jPanel2;
   private static javax.swing.JPanel N7_jPanel3;
   private static javax.swing.JPanel N7_jPanel4;
   private static javax.swing.JPanel N7_jPanel5;
   private static javax.swing.JPanel N7_jPanel6;
   private static javax.swing.JLabel N7_jLabel1;
   private static javax.swing.JLabel N7_jLabel2;
   private static javax.swing.JLabel N7_jLabel3;
   private static javax.swing.JLabel N7_jLabel4;
   private static javax.swing.JLabel N7_jLabel5;
   private static javax.swing.JLabel N7_jLabel6;

   // NIRS REGION 8
   private static javax.swing.JPanel N8_jPanel1;
   private static javax.swing.JPanel N8_jPanel2;
   private static javax.swing.JPanel N8_jPanel3;
   private static javax.swing.JPanel N8_jPanel4;
   private static javax.swing.JPanel N8_jPanel5;
   private static javax.swing.JPanel N8_jPanel6;
   private static javax.swing.JLabel N8_jLabel1;
   private static javax.swing.JLabel N8_jLabel2;
   private static javax.swing.JLabel N8_jLabel3;
   private static javax.swing.JLabel N8_jLabel4;
   private static javax.swing.JLabel N8_jLabel5;
   private static javax.swing.JLabel N8_jLabel6;

    // End of variables declaration//GEN-END:variables
}
